# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: circleci/openjdk:8-jdk-browsers

    steps:
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
      - name: show files
        run: ls
      - name: Run tests
        run: mvn clean test
      - name: generate report
        run: mvn allure:report